### PR TITLE
Smart delta deployments

### LINKED ISSUE #1349: Smarter delta deployments
So far delta deployment works pretty sttaight forward: they build a delta package via comparison from git and then intersect the original progect package xml with the delta ones.

I've encountered a problem several times: some changes in branch were not complete. The delta deployment worked well because it only deployed changes that were made. The complete deployment failed afterwards because of missing but reuquired further changes.

Examples:
- One of picklis values is deleted/deactivated but recordtypes still contain assignment of tha value. Delta deployment deploys only the field and this works, complete deployment fails because it also deploys the record types having a reference to that value.
- Some section is removed from layout or something similar. Translations however still contan translations for it. Same ways delta eployment works but not the complete deployment.

The exact aim here: I want the delty dry-run deployment to fail reliably when a dev-branch contains some corrupt changes before I merge and run the complete deployment to a major org.

I see 2 possible solutions:
1. Forbid delta deployment when certain changes are detected.
2. Extend the delta deployment with addiotinal, hardly related metadata.

I see the 2nd way more user friendly. Afaik, this is what also what gearset does.

As additional requirements I can see:
- The feature can be activated by an addiotinal flag
- The dependencies relations should be easily maintainable in a separate file (not just a bunch of if-else)

Current set of rules:
| Change in delta package | Will be added | Example to solve |
| - | - | - |
| Layout | CustomObjectTranslation | Some section deleted from Layout, but remains in translation ⭐ |
| ValidationRule | CustomObjectTranslation | Some error message translation references mising validation rule |
| QuickAction | CustomObjectTranslation | Action renamed, translation becomes orfan |
| RecordType | CustomObjectTranslation | Recordtype deleted ❓|
| CustomField | CustomObjectTranslation | Picklist value deleted/deatvicated/renamed |
| CustomLabel, CustomPageWebLink, CustomTab, ReportType| Translation| Any changes tha was perfomred in the metadata but not reflected in translations ❓  |
| CustomMetadata | All fields of related __mdt Object| When structure changes was only reflected in data ❓|
| CustomField of a custom metadata object| all CustomMetadata records | When some changes were reflected only in schema but not in records|
| CustomField of a normal sobject | all object's RecordType | Picklist value deleted/deactivated but remains in record type mapping ⭐ |
| CustomField of a normal sobject | CustomObjectTranslation |  Picklist value deleted/deactivated but remains in translations |
| CustomField of Opportunity, Account, Contact, Lead | LeadConvertSettings | A Lead field is changed (e.g. precision) corresponding filed of Opportunity was not, only full deployment with LeadConvertSettings shows the PRECISION_MISMATCH error |

❓ - not sure if the scenario realistic
⭐ - scenario was observed in real life

### PR DESCRIPTION
**Pull request by step307**
Resolves #1349

### CODE REVIEW

**Comment by step307** [comment]
@nvuillam , I think I finished at least with the ideas I had. Currently implemented extension rules are listed in the initial issue description as a table.
1. Do you have any further ideas about dependencies to add?
2. Maybe some rules are too much? I've marked the ones I've observed and I am pretty sure about, as well as the ones I doubt.
3. Should I update the documentation with the new flag, or would you prefer this feature to be hidden—very beta—for now?

**Comment by nvuillam** [comment]
@step307 i did not forget this great PR, just crazy times.... i try to look at it tonight ^^

**Comment by nvuillam** [comment]
@step307 if u want to help me, you can already document what you did in this page so it'll be easier to understand ^^
(and it will be necessary for users later anyway ^^)

https://github.com/hardisgroupcom/sfdx-hardis/blob/main/docs/salesforce-ci-cd-config-delta-deployment.md

File: src/common/utils/deltaUtils.ts [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+    "RecordType" : dotSeparatedObjectToObjectTranslation,
+    "CustomMetadata" : [allCustomFields],
+    "CustomLabel" : globalTranslations,
+    "CustomPageWebLink" : globalTranslations,
+    "CustomTab" : globalTranslations,
+    "ReportType" : globalTranslations,
+    "CustomField" : [allObjectRecordTypes, allCustomMetadataRecords, dotSeparatedObjectToObjectTranslation],
+  };
+  
+  const xml = await parseXmlFile(deltaXmlFile);
```
Comment (nvuillam) [inline src/common/utils/deltaUtils.ts:156]: you also have methods parsePackageXmlFile and writePackageXmlFile , that are more handy :)

Comment (step307) [reply src/common/utils/deltaUtils.ts]: done

**Comment by nvuillam** [comment]
@step307 I pushed little refactorings + doc in new commits, please can you test again ? :)

If your tests are successful, I'll merge the PR :)

**Comment by step307** [comment]
@nvuillam Pulled and retested successfully 👍
